spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    org.hibernate.SQL: info
decorator:
  datasource:
    p6spy:
      enable-logging: true
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    org.hibernate.SQL: info
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
decorator:
  datasource:
    p6spy:
      enable-logging: false

