spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000

    open-in-view: false

logging:
  level:
    org.hibernate.SQL: info
