spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/feed
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug